# Generated by Django 3.0.6 on 2020-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officeitems',
            fields=[
                ('idoffice', models.IntegerField(blank=True, db_column='idOffice', primary_key=True, serialize=False)),
                ('addresslocality', models.TextField(blank=True, db_column='addressLocality', null=True)),
                ('addressregion', models.TextField(blank=True, db_column='addressRegion', null=True)),
                ('postalcode', models.IntegerField(blank=True, db_column='postalCode', null=True)),
                ('streetaddress', models.TextField(blank=True, db_column='streetAddress', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('telephone', models.TextField(blank=True, null=True)),
                ('openinghours', models.TextField(blank=True, db_column='openingHours', null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('audtimestamp', models.TextField(blank=True, db_column='audTimestamp', null=True)),
            ],
            options={
                'db_table': 'OfficeItems',
                'managed': False,
            },
        ),
    ]
